// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTB.SocSit.Yalynnyi.Ispaniuk.Infrastructure.Database;

#nullable disable

namespace UTB.SocSit.Yalynnyi.Ispaniuk.Infrastructure.Migrations
{
    [DbContext(typeof(SocSitDbContext))]
    [Migration("20241217112918_alter_indentity_user")]
    partial class alter_indentity_user
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UTB.SocSit.Yalynnyi.Ispaniuk.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            PostID = 1,
                            Text = "Hello there",
                            UserID = 2
                        },
                        new
                        {
                            ID = 2,
                            PostID = 1,
                            Text = "Cool",
                            UserID = 4
                        },
                        new
                        {
                            ID = 3,
                            PostID = 1,
                            Text = "New era of social comunication begins today",
                            UserID = 5
                        },
                        new
                        {
                            ID = 4,
                            PostID = 5,
                            Text = "Nice job, keep going",
                            UserID = 4
                        },
                        new
                        {
                            ID = 5,
                            PostID = 4,
                            Text = "Cool place",
                            UserID = 5
                        });
                });

            modelBuilder.Entity("UTB.SocSit.Yalynnyi.Ispaniuk.Domain.Entities.Follow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("FollowerID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Follow");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FollowerID = 2,
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            FollowerID = 2,
                            UserID = 1
                        },
                        new
                        {
                            ID = 3,
                            FollowerID = 3,
                            UserID = 1
                        },
                        new
                        {
                            ID = 4,
                            FollowerID = 4,
                            UserID = 1
                        },
                        new
                        {
                            ID = 5,
                            FollowerID = 1,
                            UserID = 2
                        },
                        new
                        {
                            ID = 6,
                            FollowerID = 4,
                            UserID = 2
                        },
                        new
                        {
                            ID = 7,
                            FollowerID = 5,
                            UserID = 2
                        },
                        new
                        {
                            ID = 8,
                            FollowerID = 5,
                            UserID = 4
                        },
                        new
                        {
                            ID = 9,
                            FollowerID = 4,
                            UserID = 5
                        },
                        new
                        {
                            ID = 10,
                            FollowerID = 4,
                            UserID = 3
                        });
                });

            modelBuilder.Entity("UTB.SocSit.Yalynnyi.Ispaniuk.Domain.Entities.Media", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Media");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Link = "/media/4_1.jpg",
                            PostID = 4
                        },
                        new
                        {
                            ID = 2,
                            Link = "/media/4_2.jpg",
                            PostID = 4
                        },
                        new
                        {
                            ID = 3,
                            Link = "/media/4_3.jpg",
                            PostID = 4
                        },
                        new
                        {
                            ID = 4,
                            Link = "/media/5_1.mp4",
                            PostID = 5
                        });
                });

            modelBuilder.Entity("UTB.SocSit.Yalynnyi.Ispaniuk.Domain.Entities.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Text = "This is the first post on this network. Wow",
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            Text = "Hello world",
                            UserID = 2
                        },
                        new
                        {
                            ID = 3,
                            Text = "Let's try something new. What about this?",
                            UserID = 4
                        },
                        new
                        {
                            ID = 4,
                            Text = "My the latest photos from NA",
                            UserID = 2
                        },
                        new
                        {
                            ID = 5,
                            Text = "My first video from drone. What's your score?",
                            UserID = 3
                        });
                });

            modelBuilder.Entity("UTB.SocSit.Yalynnyi.Ispaniuk.Domain.Entities.Reaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Like")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Reaction");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Like = true,
                            PostID = 1,
                            UserID = 2
                        },
                        new
                        {
                            ID = 2,
                            Like = true,
                            PostID = 1,
                            UserID = 4
                        },
                        new
                        {
                            ID = 3,
                            Like = true,
                            PostID = 2,
                            UserID = 1
                        },
                        new
                        {
                            ID = 4,
                            Like = true,
                            PostID = 4,
                            UserID = 1
                        },
                        new
                        {
                            ID = 5,
                            Like = true,
                            PostID = 4,
                            UserID = 5
                        },
                        new
                        {
                            ID = 6,
                            Like = true,
                            PostID = 4,
                            UserID = 2
                        },
                        new
                        {
                            ID = 7,
                            Like = true,
                            PostID = 4,
                            UserID = 4
                        },
                        new
                        {
                            ID = 8,
                            Like = true,
                            PostID = 5,
                            UserID = 4
                        },
                        new
                        {
                            ID = 9,
                            Like = true,
                            PostID = 5,
                            UserID = 1
                        },
                        new
                        {
                            ID = 10,
                            Like = true,
                            PostID = 5,
                            UserID = 2
                        },
                        new
                        {
                            ID = 11,
                            Like = false,
                            PostID = 4,
                            UserID = 3
                        });
                });

            modelBuilder.Entity("UTB.SocSit.Yalynnyi.Ispaniuk.Infrastructure.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nickname")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "26aba3e9-86ba-492a-a525-da131a46f8cf",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "orpha_terry@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Orpha Terry",
                            Nickname = "orpha_terry",
                            PhoneNumberConfirmed = false,
                            Photo = "/img/user/default.jpg",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5f84c7c5-cfd4-482f-b25f-85c3bc991069",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marta.berge47@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Marta Berge",
                            Nickname = "marta_berge",
                            PhoneNumberConfirmed = false,
                            Photo = "/img/user/default.jpg",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a8dfc092-d16b-40a8-88c4-2799e2dcc0a1",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jamir_kshlerin@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Jamir Kshlerin",
                            Nickname = "j_kshlerin",
                            PhoneNumberConfirmed = false,
                            Photo = "/img/user/default.jpg",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c1a31b25-4ac9-4bad-8054-a00871222cf4",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rico_spinka66@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Rico Spinka",
                            Nickname = "rico_spinka",
                            PhoneNumberConfirmed = false,
                            Photo = "/img/user/default.jpg",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cc67af2d-cb55-41e8-a371-6c93892c3595",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ottilie.emmerich43@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Ottilie Emmerich",
                            Nickname = "emmerich43",
                            PhoneNumberConfirmed = false,
                            Photo = "/img/user/default.jpg",
                            TwoFactorEnabled = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
