// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTB.SocSit.Yalynnyi.Ispaniuk.Infrastructure.Database;

#nullable disable

namespace UTB.SocSit.Yalynnyi.Ispaniuk.Infrastructure.Migrations
{
    [DbContext(typeof(SocSitDbContext))]
    [Migration("20250113140931_alter-posts-seeding")]
    partial class alterpostsseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UTB.SocSit.Yalynnyi.Ispaniuk.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            PostID = 1,
                            Text = "Hello there",
                            UserID = 2
                        },
                        new
                        {
                            ID = 2,
                            PostID = 1,
                            Text = "Cool",
                            UserID = 4
                        },
                        new
                        {
                            ID = 3,
                            PostID = 1,
                            Text = "New era of social comunication begins today",
                            UserID = 5
                        },
                        new
                        {
                            ID = 4,
                            PostID = 5,
                            Text = "Nice job, keep going",
                            UserID = 4
                        },
                        new
                        {
                            ID = 5,
                            PostID = 4,
                            Text = "Cool place",
                            UserID = 5
                        });
                });

            modelBuilder.Entity("UTB.SocSit.Yalynnyi.Ispaniuk.Domain.Entities.Follow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("FollowerID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Follow");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FollowerID = 2,
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            FollowerID = 2,
                            UserID = 1
                        },
                        new
                        {
                            ID = 3,
                            FollowerID = 3,
                            UserID = 1
                        },
                        new
                        {
                            ID = 4,
                            FollowerID = 4,
                            UserID = 1
                        },
                        new
                        {
                            ID = 5,
                            FollowerID = 1,
                            UserID = 2
                        },
                        new
                        {
                            ID = 6,
                            FollowerID = 4,
                            UserID = 2
                        },
                        new
                        {
                            ID = 7,
                            FollowerID = 5,
                            UserID = 2
                        },
                        new
                        {
                            ID = 8,
                            FollowerID = 5,
                            UserID = 4
                        },
                        new
                        {
                            ID = 9,
                            FollowerID = 4,
                            UserID = 5
                        },
                        new
                        {
                            ID = 10,
                            FollowerID = 4,
                            UserID = 3
                        });
                });

            modelBuilder.Entity("UTB.SocSit.Yalynnyi.Ispaniuk.Domain.Entities.Media", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Media");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Link = "/media/4_1.jpg",
                            PostID = 4
                        },
                        new
                        {
                            ID = 2,
                            Link = "/media/4_2.jpg",
                            PostID = 4
                        },
                        new
                        {
                            ID = 3,
                            Link = "/media/4_3.jpg",
                            PostID = 4
                        },
                        new
                        {
                            ID = 4,
                            Link = "/media/5_1.mp4",
                            PostID = 5
                        });
                });

            modelBuilder.Entity("UTB.SocSit.Yalynnyi.Ispaniuk.Domain.Entities.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Text = "This is post number 1 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 2,
                            Text = "This is post number 2 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 3,
                            Text = "This is post number 3 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 4,
                            Text = "This is post number 4 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 5,
                            Text = "This is post number 5 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 6,
                            Text = "This is post number 6 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 7,
                            Text = "This is post number 7 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 8,
                            Text = "This is post number 8 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 9,
                            Text = "This is post number 9 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 10,
                            Text = "This is post number 10 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 11,
                            Text = "This is post number 11 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 12,
                            Text = "This is post number 12 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 13,
                            Text = "This is post number 13 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 14,
                            Text = "This is post number 14 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 15,
                            Text = "This is post number 15 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 16,
                            Text = "This is post number 16 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 17,
                            Text = "This is post number 17 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 18,
                            Text = "This is post number 18 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 19,
                            Text = "This is post number 19 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 20,
                            Text = "This is post number 20 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 21,
                            Text = "This is post number 21 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 22,
                            Text = "This is post number 22 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 23,
                            Text = "This is post number 23 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 24,
                            Text = "This is post number 24 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 25,
                            Text = "This is post number 25 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 26,
                            Text = "This is post number 26 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 27,
                            Text = "This is post number 27 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 28,
                            Text = "This is post number 28 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 29,
                            Text = "This is post number 29 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 30,
                            Text = "This is post number 30 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 31,
                            Text = "This is post number 31 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 32,
                            Text = "This is post number 32 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 33,
                            Text = "This is post number 33 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 34,
                            Text = "This is post number 34 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 35,
                            Text = "This is post number 35 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 36,
                            Text = "This is post number 36 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 37,
                            Text = "This is post number 37 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 38,
                            Text = "This is post number 38 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 39,
                            Text = "This is post number 39 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 40,
                            Text = "This is post number 40 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 41,
                            Text = "This is post number 41 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 42,
                            Text = "This is post number 42 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 43,
                            Text = "This is post number 43 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 44,
                            Text = "This is post number 44 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 45,
                            Text = "This is post number 45 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 46,
                            Text = "This is post number 46 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 47,
                            Text = "This is post number 47 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 48,
                            Text = "This is post number 48 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 49,
                            Text = "This is post number 49 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 50,
                            Text = "This is post number 50 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 51,
                            Text = "This is post number 51 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 52,
                            Text = "This is post number 52 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 53,
                            Text = "This is post number 53 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 54,
                            Text = "This is post number 54 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 55,
                            Text = "This is post number 55 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 56,
                            Text = "This is post number 56 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 57,
                            Text = "This is post number 57 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 58,
                            Text = "This is post number 58 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 59,
                            Text = "This is post number 59 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 60,
                            Text = "This is post number 60 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 61,
                            Text = "This is post number 61 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 62,
                            Text = "This is post number 62 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 63,
                            Text = "This is post number 63 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 64,
                            Text = "This is post number 64 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 65,
                            Text = "This is post number 65 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 66,
                            Text = "This is post number 66 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 67,
                            Text = "This is post number 67 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 68,
                            Text = "This is post number 68 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 69,
                            Text = "This is post number 69 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 70,
                            Text = "This is post number 70 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 71,
                            Text = "This is post number 71 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 72,
                            Text = "This is post number 72 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 73,
                            Text = "This is post number 73 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 74,
                            Text = "This is post number 74 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 75,
                            Text = "This is post number 75 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 76,
                            Text = "This is post number 76 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 77,
                            Text = "This is post number 77 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 78,
                            Text = "This is post number 78 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 79,
                            Text = "This is post number 79 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 80,
                            Text = "This is post number 80 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 81,
                            Text = "This is post number 81 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 82,
                            Text = "This is post number 82 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 83,
                            Text = "This is post number 83 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 84,
                            Text = "This is post number 84 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 85,
                            Text = "This is post number 85 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 86,
                            Text = "This is post number 86 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 87,
                            Text = "This is post number 87 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 88,
                            Text = "This is post number 88 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 89,
                            Text = "This is post number 89 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 90,
                            Text = "This is post number 90 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 91,
                            Text = "This is post number 91 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 92,
                            Text = "This is post number 92 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 93,
                            Text = "This is post number 93 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 94,
                            Text = "This is post number 94 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 95,
                            Text = "This is post number 95 on this network. Enjoy reading!",
                            UserID = 1
                        },
                        new
                        {
                            ID = 96,
                            Text = "This is post number 96 on this network. Enjoy reading!",
                            UserID = 2
                        },
                        new
                        {
                            ID = 97,
                            Text = "This is post number 97 on this network. Enjoy reading!",
                            UserID = 3
                        },
                        new
                        {
                            ID = 98,
                            Text = "This is post number 98 on this network. Enjoy reading!",
                            UserID = 4
                        },
                        new
                        {
                            ID = 99,
                            Text = "This is post number 99 on this network. Enjoy reading!",
                            UserID = 5
                        },
                        new
                        {
                            ID = 100,
                            Text = "This is post number 100 on this network. Enjoy reading!",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("UTB.SocSit.Yalynnyi.Ispaniuk.Domain.Entities.Reaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Like")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Reaction");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Like = true,
                            PostID = 1,
                            UserID = 2
                        },
                        new
                        {
                            ID = 2,
                            Like = true,
                            PostID = 1,
                            UserID = 4
                        },
                        new
                        {
                            ID = 3,
                            Like = true,
                            PostID = 2,
                            UserID = 1
                        },
                        new
                        {
                            ID = 4,
                            Like = true,
                            PostID = 4,
                            UserID = 1
                        },
                        new
                        {
                            ID = 5,
                            Like = true,
                            PostID = 4,
                            UserID = 5
                        },
                        new
                        {
                            ID = 6,
                            Like = true,
                            PostID = 4,
                            UserID = 2
                        },
                        new
                        {
                            ID = 7,
                            Like = true,
                            PostID = 4,
                            UserID = 4
                        },
                        new
                        {
                            ID = 8,
                            Like = true,
                            PostID = 5,
                            UserID = 4
                        },
                        new
                        {
                            ID = 9,
                            Like = true,
                            PostID = 5,
                            UserID = 1
                        },
                        new
                        {
                            ID = 10,
                            Like = true,
                            PostID = 5,
                            UserID = 2
                        },
                        new
                        {
                            ID = 11,
                            Like = false,
                            PostID = 4,
                            UserID = 3
                        });
                });

            modelBuilder.Entity("UTB.SocSit.Yalynnyi.Ispaniuk.Infrastructure.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("UTB.SocSit.Yalynnyi.Ispaniuk.Infrastructure.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d5e18436-1d5c-4145-887e-51ef41fa3638",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "orpha_terry@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Orpha Terry",
                            PhoneNumberConfirmed = false,
                            Photo = "/img/user/default.jpg",
                            TwoFactorEnabled = false,
                            UserName = "orpha_terry"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6dcbf4f7-38d7-4ce2-94bf-26758717f9e0",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marta.berge47@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Marta Berge",
                            PhoneNumberConfirmed = false,
                            Photo = "/img/user/default.jpg",
                            TwoFactorEnabled = false,
                            UserName = "marta_berge"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d8bf7b3b-4430-4f69-8a1d-26237ba67a52",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jamir_kshlerin@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Jamir Kshlerin",
                            PhoneNumberConfirmed = false,
                            Photo = "/img/user/default.jpg",
                            TwoFactorEnabled = false,
                            UserName = "j_kshlerin"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "feff3194-e445-46f6-b119-12d6f8481d20",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rico_spinka66@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Rico Spinka",
                            PhoneNumberConfirmed = false,
                            Photo = "/img/user/default.jpg",
                            TwoFactorEnabled = false,
                            UserName = "rico_spinka"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "44d8f454-fc97-4357-a1e0-488b0e994741",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ottilie.emmerich43@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Ottilie Emmerich",
                            PhoneNumberConfirmed = false,
                            Photo = "/img/user/default.jpg",
                            TwoFactorEnabled = false,
                            UserName = "emmerich43"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("UTB.SocSit.Yalynnyi.Ispaniuk.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("UTB.SocSit.Yalynnyi.Ispaniuk.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("UTB.SocSit.Yalynnyi.Ispaniuk.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("UTB.SocSit.Yalynnyi.Ispaniuk.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UTB.SocSit.Yalynnyi.Ispaniuk.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("UTB.SocSit.Yalynnyi.Ispaniuk.Infrastructure.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
